// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjugqrifeecoxewscqdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdWdxcmlmZWVjb3hld3NjcWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjA0MzEsImV4cCI6MjA3MTEzNjQzMX0.TVcsnCS8iI5_oJQhdjo1KTdpFhTwF2HpbE4IflCqQng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});